// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // 런타임 쿼리용 URL (pgbouncer 커넥션 풀링, 포트 6543)
    url: process.env["DATABASE_URL"],
    // 마이그레이션 전용 URL (직접 연결, 포트 5432)
    directUrl: process.env["DIRECT_URL"],
  },
});
