// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma 7.x: 마이그레이션 CLI는 이 url을 사용합니다.
    // Direct connection(포트 5432)을 사용해야 pgbouncer 제한을 피할 수 있습니다.
    // 런타임 쿼리는 src/lib/prisma.ts에서 DATABASE_URL(포트 6543, pgbouncer)을 사용합니다.
    url: process.env["DIRECT_URL"],
  },
});
